### ISSUE TITLE
Feature Request: add Estimated halving date...

### ISSUE THREAD

**Issue by Tjossul** [8go/bitcoin-stock-to-flow#1]
Hi,

do you know how this is calculated? 

Maybe it would be a good enhancement to your script.

Regards.
Sebastian.

**Comment by 8go** [comment]
Thanks @Tjossul 
Good idea. 
I will have a look at that when I have some spare time. Stay posted.

**Comment by 8go** [comment]
Implemented in commit fe4da671eab189408da46d1298c7d02312effc9e
